import ajv from '../libs/ajv'

const user = {
  $id: '/user.json',
  type: 'object',
  properties: {
    id: { type: 'string' },
    uuid: { type: 'string' },
    firstName: { type: ['string', 'null'] },
    lastName: { type: ['string', 'null'] },
    email: { type: ['string', 'null'] },
    emailVerified: { type: 'boolean' },
    phone: { type: ['string', 'null'] },
    phoneCode: { type: ['string', 'null'] },
    phoneVerified: { type: 'boolean' },
    dateOfBirth: { type: ['string', 'null'] },
    gender: { type: ['string', 'null'] },
    locale: { type: ['string', 'null'] },
    signInCount: { type: 'number' },
    playerType: { type: 'string' },
    // TODO: It shoud be ipv4
    signInIp: { type: ['string', 'null'] },
    parentType: { type: ['string', 'null'] },
    parentId: { type: ['number', 'null'] },
    userName: { type: ['string', 'null'] },
    countryCode: { type: ['string', 'null'] },
    active: { type: 'boolean' },
    selfExclusion: { type: ['string', 'null'] },
    deletedAt: { type: ['string', 'null'], format: 'date-time' },
    vipLevel: { type: 'number' },
    nickName: { type: ['string', 'null'] },
    disabledAt: { type: ['string', 'null'], format: 'date-time' },
    disabledByType: { type: ['string', 'null'] },
    disabledById: { type: ['number', 'null'] },
    profilePicture: { type: 'string' },
    expireIn: { type: 'string', format: 'date-time' },
    nonce: { type: ['string', 'null'] },
    ethereumAddress: { type: ['string', 'null'] },
    twoFactorSecretKey: { type: ['string', 'null'] },
    twoFactorEnabled: { type: 'boolean' },
    referralCode: { type: ['string', 'null'] },
    applicantId: { type: ['string', 'null'] },
    sumsubKycStatus: { type: ['string', 'null'] },
    kycVerificationLevel: { type: ['string', 'null'] },
    referrerCode: { type: ['string', 'null'] },
    referralLink: { type: ['string', 'null'] },
    profileImageUrl: { type: ['string', 'null'] },
    isPrivate: { type: 'boolean' },
    createdAt: { type: 'string', format: 'date-time' },
    updatedAt: { type: 'string', format: 'date-time' },
    lastLogin: { type: ['string', 'null'], format: 'date-time' },
    loginMethod: { type: ['string', 'null'] },
    rankingLevel: { type: ['string', 'null'] },
    affiliateById: { type: ['string', 'null'] },
    affiliateId: { type: ['string', 'null'] },
    isChatModerator: { type: 'boolean' },
    isLimit: { type: 'boolean' },
  }
}

ajv.addSchema(user)
